# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 23:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_Ambassdors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('college_name', models.CharField(max_length=100)),
                ('college_address', models.CharField(max_length=300)),
                ('ca_code', models.CharField(max_length=50)),
                ('reason_ca', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Campus Ambassdors',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('type', models.CharField(choices=[('Technical', 'Technical'), ('Cultural', 'Cultural'), ('Management', 'Management')], max_length=30)),
                ('type1', models.CharField(choices=[('F', 'Flagship'), ('Ma', 'Major'), ('Mi', 'Minor')], default='F', max_length=30)),
                ('type2', models.CharField(choices=[('1', 'Home'), ('2', 'NO')], default='2', max_length=10)),
                ('fee', models.CharField(choices=[('CM', 'CM'), ('T', 'T')], default='CM', max_length=5)),
                ('min_participants', models.IntegerField()),
                ('max_participants', models.IntegerField()),
                ('prize', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='events_logo')),
                ('description', models.CharField(default='', max_length=500)),
                ('time', models.TimeField()),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('venue', models.CharField(max_length=10)),
                ('contact_name1', models.CharField(default='', max_length=30)),
                ('contact_phone1', models.BigIntegerField(unique=True)),
                ('contact_image1', models.ImageField(blank=True, upload_to='event_contact')),
                ('contact_email1', models.EmailField(default='', max_length=254)),
                ('contact_name2', models.CharField(default='', max_length=30)),
                ('contact_phone2', models.BigIntegerField(unique=True)),
                ('contact_image2', models.ImageField(blank=True, upload_to='event_contact')),
                ('contact_email2', models.EmailField(default='', max_length=254)),
                ('rules', models.FileField(blank=True, upload_to='rules')),
                ('sponsor1', models.ImageField(blank=True, upload_to='events_sponsors')),
                ('sponsor2', models.ImageField(blank=True, upload_to='events_sponsors')),
                ('sponsor3', models.ImageField(blank=True, upload_to='events_sponsors')),
                ('sponsor4', models.ImageField(blank=True, upload_to='events_sponsors')),
                ('one_liner', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
        migrations.CreateModel(
            name='Pro_Night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('main_image', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_1', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_2', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_3', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_4', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_5', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_6', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_7', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_8', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_9', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_10', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_11', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_12', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_13', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_14', models.ImageField(blank=True, upload_to='pro_nights')),
                ('small_image_15', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_1', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_2', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_3', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_4', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_5', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_6', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_7', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_8', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_9', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_10', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_11', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_12', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_13', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_14', models.ImageField(blank=True, upload_to='pro_nights')),
                ('large_image_15', models.ImageField(blank=True, upload_to='pro_nights')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Pro_Night',
            },
        ),
        migrations.CreateModel(
            name='single_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('event_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Title Sponsor'), ('2', 'Online Media Sponsors'), ('3', 'Normal Sponsor'), ('4', 'Event Sponsor')], max_length=20)),
                ('name', models.CharField(default='', max_length=30)),
                ('name_shown', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='sponsors')),
                ('url', models.URLField(default='')),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Core'), ('2', 'Sponsorship'), ('3', 'Design'), ('4', 'PR'), ('5', 'TM'), ('6', 'Technical'), ('7', 'Operation'), ('8', 'Decoration'), ('9', 'Social Media'), ('10', 'Content Writing')], max_length=20)),
                ('name', models.CharField(default='', max_length=30)),
                ('facebook', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='team')),
                ('position', models.CharField(default='', max_length=30)),
                ('tag_line', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], max_length=6)),
                ('contact', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('Terms_and_Conditions', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='single_event',
            unique_together=set([('username', 'event_name')]),
        ),
    ]
