# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180218_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus_Ambassdors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('college_name', models.CharField(max_length=100)),
                ('college_address', models.CharField(max_length=300)),
                ('ca_code', models.CharField(max_length=50)),
                ('reason_ca', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Campus Ambassdors',
            },
        ),
        migrations.DeleteModel(
            name='Campus_Ambassdor',
        ),
    ]
