# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180222_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Title Sponsor'), ('2', 'Online Media Sponsors'), ('3', 'Normal Sponsor'), ('4', 'Event Sponsor')], max_length=20)),
                ('name', models.CharField(default='', max_length=30)),
                ('name_shown', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='sponsors')),
                ('url', models.URLField(default='')),
            ],
            options={
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Core'), ('2', 'Sponsorship'), ('3', 'Design'), ('4', 'PR'), ('5', 'TM'), ('6', 'Technical'), ('7', 'Operation'), ('8', 'Decoration'), ('9', 'Social Media'), ('10', 'Content Writing')], max_length=20)),
                ('name', models.CharField(default='', max_length=30)),
                ('facebook', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('linkedin', models.URLField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='team')),
                ('position', models.CharField(default='', max_length=30)),
                ('tag_line', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
